name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install clang
    - name: Build with ${{ matrix.cc }}
      run: |
        ./configure
        CC=${{ matrix.cc }} make re

  testsuite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
    - name: Run testsuite
      run: |
        ./configure
        make test
